<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" dir="ltr" lang="hu" xml:lang="hu">
<head>
<script type="text/javascript">
            function get_width(id, rand_num)
            {
                var div_planet_name = document.getElementById('planet_name_div_'+id+'_'+rand_num);
                var takaro_div = document.getElementById('takaro_'+id+'_'+rand_num);
                var flag_div = document.getElementById('flag_'+id+'_'+rand_num);
                var alliance_div = document.getElementById('alliance_'+id+'_'+rand_num);

                var width = div_planet_name.offsetWidth;

                if (width > 90) {
                    div_planet_name.style.width = '90px';
                    takaro_div.style.visibility = 'visible';
                    takaro_div.style.left = '146px';
                }
                var width_new = div_planet_name.offsetWidth;

                flag_div.style.left = (64+width_new+12)+'px';
                alliance_div.style.left = (64+width_new+12+23)+'px';
            }
         </script>
<meta http-equiv="content-type" content="text/html; charset=utf-8" />
<meta http-equiv="content-style-type" content="text/css" />
<meta http-equiv="content-language" content="hu" />
<meta http-equiv="imagetoolbar" content="no" />
<meta name="resource-type" content="document" />
<meta name="distribution" content="global" />
<meta name="copyright" content="2000, 2002, 2005, 2007 phpBB Group" />
<meta name="keywords" content="" />
<meta name="description" content="" />
<meta http-equiv="X-UA-Compatible" content="IE=EmulateIE7" />

<title>galacticax.com &bull; Gyakran ismételt kérdések</title>



<!--
	phpBB style name: prosilver
	Based on style:   prosilver (this is the default phpBB3 style)
	Original author:  Tom Beddard ( http://www.subBlue.com/ )
	Modified by:

	NOTE: This page was generated by phpBB, the free open-source bulletin board package.
	      The phpBB Group is not responsible for the content of this page and forum. For more information
	      about phpBB please visit http://www.phpbb.com
-->

<script type="text/javascript">
// <![CDATA[
	var jump_page = 'Add meg annak az oldalnak a számát, ahová menni szeretnél:';
	var on_page = '';
	var per_page = '';
	var base_url = '';
	var style_cookie = 'phpBBstyle';
	var style_cookie_settings = '; path=/; domain=.galacticax.com';
	var onload_functions = new Array();
	var onunload_functions = new Array();

	

	/**
	* Find a member
	*/
	function find_username(url)
	{
		popup(url, 760, 570, '_usersearch');
		return false;
	}

	/**
	* New function for handling multiple calls to window.onload and window.unload by pentapenguin
	*/
	window.onload = function()
	{
		for (var i = 0; i < onload_functions.length; i++)
		{
			eval(onload_functions[i]);
		}
	}

	window.onunload = function()
	{
		for (var i = 0; i < onunload_functions.length; i++)
		{
			eval(onunload_functions[i]);
		}
	}

// ]]>
</script>
<script type="text/javascript" src="./styles/prosilver/template/jquery.js?r=1"></script>
<script type="text/javascript" src="./styles/prosilver/template/styleswitcher.js?r=1"></script>
<script type="text/javascript" src="./styles/prosilver/template/forum_fn.js?r=1"></script>
<script type="text/javascript" src="./styles/prosilver/template/fade.js?r=1"></script>
<script type="text/javascript" src="./styles/prosilver/template/time.js?r=1"></script>
<script type="text/javascript" src="/Themes/Scripts/popup.js?r=1"></script>
<script type="text/javascript" src="/Themes/Scripts/selectbox/jquery.selectbox-0.3.js?r=1"></script>
<link href="./styles/prosilver/theme/digitrox.css" rel="stylesheet" type="text/css" />

<link href="./styles/prosilver/theme/gal6.css?r=2" rel="stylesheet" type="text/css" />
<link href="./styles/prosilver/theme/galform.css?r=1" rel="stylesheet" type="text/css" />
<link href="./styles/prosilver/theme/print.css?r=1" rel="stylesheet" type="text/css" media="print" title="printonly" />
<link href="./style.php?id=1&amp;lang=hu&r=1" rel="stylesheet" type="text/css" media="screen, projection" />

<link href="./styles/prosilver/theme/normal.css?r=1" rel="stylesheet" type="text/css" title="A" />
<link href="./styles/prosilver/theme/medium.css?r=1" rel="alternate stylesheet" type="text/css" title="A+" />
<link href="./styles/prosilver/theme/large.css?r=1" rel="alternate stylesheet" type="text/css" title="A++" />
<script type="text/javascript" src="jquery.js?r=1"></script>
<script type="text/javascript" src="fade.js?r=1"></script>


<script type="text/javascript">
  if(self==top){
    //window.parent.location.href = 'http://'+document.domain;
  }

    //document.domain = "galacticax.com";
    function setFrameHeight(){
        window.parent.setForumFrameDef();
        var height = $(document).height();
        window.parent.setForumFrame(height);
    }

    $(document).ready(function(){
        if (typeof window.parent.setForumFrameDef == 'function' &&
            typeof window.parent.setForumFrame == 'function'){
                setFrameHeight();
        }
    });
</script>

</head>

<body id="phpbb" class="section-faq ltr">






<p class="left top-gal6time"style="margin-left:13px;color: #FFE3A5;">Utolsó látogatás: <span><span style='color: #07B836;'>GXT:25:1597:12</span> <span style='color: white;' class='time_counter'>(11 órája 35 perce)</span></span></p>


<!--[if IE 6]>
<style type="text/css">
#fTabs .default .right li a{
	padding: 9px 5px;
}
</style>
<![endif]-->
<script type="text/javascript">
$(document).ready(function(){
	$("#fTabs #ftTop li").hover(function(){
		$( this ).each(function( c, e ){
			if( $(this).hasClass('active') ){ return; }
			$( this ).addClass('hover');
		});
	}, function(){
		$( this ).each(function( c, e ){
			$( this ).removeClass('hover');
		});
	});
});
</script>
<div id="fTabs">
    <div id="ftTop" class="default digitrox">
        <div class="left">
            <ul>
                <li class="">
                    <div>
                        <div>
                            <a href="viewforum.php?f=129"><b>Közös fórum </b></a>
                        </div>
                    </div>
                </li>
                <li class="">
                    <div>
                        <div>
                            <a href="viewforum.php?f=8109"><b>Galaxis fórum </b></a>
                        </div>
                    </div>
                </li>
                <li class="">
                    <div>
                        <div>
                            <a href="viewforum.php?f=8110"><b>Szövetségi fórum </b></a>
                        </div>
                    </div>
                </li>
                <li class="">
                    <div>
                        <div>
                            <a href="viewforum.php?f="><b>Mentori fórum </b></a>
                        </div>
                    </div>
                </li>
            </ul>
        </div>
        <div class="right">
            <ul>
                <li class="">
                    <div>
                        <div>
                            <a href="ucp.php?i=prefs&mode=personal"><img src="styles/prosilver/imageset/tabs/kerek.png" border="0" /></a>
                        </div>
                    </div>
                </li>
                <li class="active right-tab">
                    <div>
                        <div>
                            <a href="faq.php"><img src="styles/prosilver/imageset/tabs/kerdo.png" border="0" /></a>
                        </div>
                    </div>
                </li>
            </ul>
        </div>
        <div class="clr"></div>
    </div>
</div>







    <div style="background-color:#1c1c1c;margin-left:10px;width:933px;">&nbsp; &nbsp;
	<div id="page-body">

		

<div style="background-color:#1c1c1c;"><h2 align="center" style="color:#FFE3A5; font-weight: bold;">Gyakran ismételt kérdések</h2></div>


<div class="panel bg1" id="faqlinks">
	<div class="inner"><span class="corners-top"><span></span></span>
		<div class="column1">
		

			<dl class="faq">
				<dt><strong style="color:white;">Belépési és regisztrációs kérdések</strong></dt>
				
					<dd><a href="#f0r0">Miért nem érem el a fórumot?</a></dd>
				
					<dd><a href="#f0r1">Miért kerülök kiléptetésre automatikusan?</a></dd>
				
					<dd><a href="#f0r2">Hogyan tudom megakadályozni, hogy mások lássák, mikor vagyok jelen?</a></dd>
				
					<dd><a href="#f0r3">Elfelejtettem a jelszavamat!</a></dd>
				
					<dd><a href="#f0r4">Korábban regisztráltam magam, azonban már nem tudok belépni?!</a></dd>
				
			</dl>
		

			<dl class="faq">
				<dt><strong style="color:white;">Felhasználói beállítások</strong></dt>
				
					<dd><a href="#f1r0">Hogyan tudom megváltoztatni a beállításaimat?</a></dd>
				
					<dd><a href="#f1r1">Hogyan jeleníthetek meg egy képet a nevem alatt?</a></dd>
				
			</dl>
		

			<dl class="faq">
				<dt><strong style="color:white;">Hozzászólással kapcsolatos kérdések</strong></dt>
				
					<dd><a href="#f2r0">Hogyan készíthetek egy új témát egy fórumban?</a></dd>
				
					<dd><a href="#f2r1">Hogyan szerkeszthetek, illetve törölhetek egy hozzászólást?</a></dd>
				
					<dd><a href="#f2r2">Hogyan készíthetek szavazást?</a></dd>
				
					<dd><a href="#f2r3">Hogyan szerkeszthetek vagy törölhetek egy szavazást?</a></dd>
				
					<dd><a href="#f2r4">Miért nem férek hozzá egy témához?</a></dd>
				
					<dd><a href="#f2r5">Miért nem tudok szavazni?</a></dd>
				
					<dd><a href="#f2r6">Miért kaptam figyelmeztetést?</a></dd>
				
					<dd><a href="#f2r7">Hogyan jelenthetek egy hozzászólást a moderátoroknak?</a></dd>
				
			</dl>
		

			<dl class="faq">
				<dt><strong style="color:white;">Formázás és téma típusok</strong></dt>
				
					<dd><a href="#f3r0">Mi az a BBCode?</a></dd>
				
					<dd><a href="#f3r1">Használhatok HTML-t?</a></dd>
				
					<dd><a href="#f3r2">Mik azok a fejecskék?</a></dd>
				
					<dd><a href="#f3r3">Küldhetek képeket?</a></dd>
				
					<dd><a href="#f3r4">Mik azok a globális közlemények?</a></dd>
				
					<dd><a href="#f3r5">Mik azok a lezárt témák?</a></dd>
				
			</dl>
		
				</div>

				<div class="column2">
			

			<dl class="faq">
				<dt><strong style="color:white;">Az UFFIH jelenléte a fórumon</strong></dt>
				
					<dd><a href="#f4r0">Ki az a Proctor Conductor?</a></dd>
				
					<dd><a href="#f4r1">Kik azok az Inspektorok?</a></dd>
				
					<dd><a href="#f4r2">Kit és hogy tudok értesíteni, ha a fórum tartalmával problémám van?</a></dd>
				
			</dl>
		

			<dl class="faq">
				<dt><strong style="color:white;">Készítők</strong></dt>
				
					<dd><a href="#f5r0">Ki készítette ezt a fórumot?</a></dd>
				
			</dl>
		
		</div>
	<span class="corners-bottom"><span></span></span></div>
</div>



<div class="clear"></div>


	<div class="panel bg2">
		<div class="inner"><span class="corners-top"><span></span></span>

		<div class="content">
                    <h2 style="color:white;">Belépési és regisztrációs kérdések</h2>
			
				<dl class="faq">
					<dt id="f0r0"><strong style="color:#FFE3A5;">Miért nem érem el a fórumot?</strong></dt>
					<dd>Ennek számos oka lehet. Először is ellenőrizd, hogy be vagy-e lépve a planétádhoz. Ha igen és nem vagy kitiltva, valamint mégsem éred el a fórumot, írj egy tikettet erről a Supportra.</dd>
				</dl>
				<hr class="dashed" />
				<dl class="faq">
					<dt id="f0r1"><strong style="color:#FFE3A5;">Miért kerülök kiléptetésre automatikusan?</strong></dt>
					<dd>Ha huzamosabb ideig nem csinálsz semmit a planétádon vagy a fórumon, akkor a rendszer kiléptet. Ilyen esetben az első új oldal betöltésekor szembesülsz vele.</dd>
				</dl>
				<hr class="dashed" />
				<dl class="faq">
					<dt id="f0r2"><strong style="color:#FFE3A5;">Hogyan tudom megakadályozni, hogy mások lássák, mikor vagyok jelen?</strong></dt>
					<dd>A Felhasználói vezérlőpultban a „Fórum beállítások” menüpont alatt található a „Jelenlét elrejtése” beállítás. Ha ezt <samp>Igen</samp>re állítod,csak a Proctor Conductor, az Inspektorok, illetve saját magad fogod látni, hogy jelen vagy-e.</dd>
				</dl>
				<hr class="dashed" />
				<dl class="faq">
					<dt id="f0r3"><strong style="color:#FFE3A5;">Elfelejtettem a jelszavamat!</strong></dt>
					<dd>Semmi pánik! A jelszavad ugyan nem lehet utólag kideríteni, de lehetőséged van újat kérni a Supporton keresztül.</dd>
				</dl>
				<hr class="dashed" />
				<dl class="faq">
					<dt id="f0r4"><strong style="color:#FFE3A5;">Korábban regisztráltam magam, azonban már nem tudok belépni?!</strong></dt>
					<dd>Keresd elő a regisztrációkor kapott e-mailt, ellenőrizd le a felhasználóneved és a jelszavad, majd próbálkozz újra. Lehetséges, hogy a rendszer vagy az UFFIH valamilyen okból kifolyólag inaktiválta az azonosítód. Végső esetben írj a Supportra.</dd>
				</dl>
				
		</div>

		<span class="corners-bottom"><span></span></span></div>
	</div>

	<div class="panel bg1">
		<div class="inner"><span class="corners-top"><span></span></span>

		<div class="content">
                    <h2 style="color:white;">Felhasználói beállítások</h2>
			
				<dl class="faq">
					<dt id="f1r0"><strong style="color:#FFE3A5;">Hogyan tudom megváltoztatni a beállításaimat?</strong></dt>
					<dd>A beállításaid megváltoztatásához kattints a Vezérlőpult gombra. Jelenleg három részre vannak bontva a lehetőségeid a Felhasználói vezérlőpultban, nézd át őket alaposan, mielőtt meghoznád a végső döntést.</dd>
				</dl>
				<hr class="dashed" />
				<dl class="faq">
					<dt id="f1r1"><strong style="color:#FFE3A5;">Hogyan jeleníthetek meg egy képet a nevem alatt?</strong></dt>
					<dd>A hozzászólások megtekintésénél a planétanév alatt a planéta képe jelenik meg, amit a planéta hadura állíthat be a Planéta Profilban. A Felhasználói Vezérlőpultban letilthatod ezek megjelenését. Jelenleg ez az opció nem engedélyezett.</dd>
				</dl>
				
		</div>

		<span class="corners-bottom"><span></span></span></div>
	</div>

	<div class="panel bg2">
		<div class="inner"><span class="corners-top"><span></span></span>

		<div class="content">
                    <h2 style="color:white;">Hozzászólással kapcsolatos kérdések</h2>
			
				<dl class="faq">
					<dt id="f2r0"><strong style="color:#FFE3A5;">Hogyan készíthetek egy új témát egy fórumban?</strong></dt>
					<dd>Ha egy fórumban új témát szeretnél nyitni, kattints a megfelelő gombra a fórumban vagy annak egy témájában. Hozzászólás küldéséhez lehet, hogy előbb regisztrálnod kell. A jogosultságaidat a fórum vagy téma oldalak alján találod meg. Például: Nyithatsz új témákat, Szavazhatsz stb.</dd>
				</dl>
				<hr class="dashed" />
				<dl class="faq">
					<dt id="f2r1"><strong style="color:#FFE3A5;">Hogyan szerkeszthetek, illetve törölhetek egy hozzászólást?</strong></dt>
					<dd>Csak azokat a hozzászólásokat szerkesztheted vagy törölheted, melyeket te küldtél. Egy hozzászólást a szerkesztés gombra kattintva tudsz módosítani. Abban az esetben, ha valaki már válaszolt a hozzászólásodra, a hozzászólásod alatt egy apró szöveg fog megjelenni, mely jelzi, a hozzászólás hányszor és ki által került szerkesztésre. Ez csak akkor fog megjelenni, ha utánad küldött már valaki egy hozzászólást, akkor nem, ha még nem válaszolt senki, illetve ha a Proctor Conductor vagy egy Inspektor szerkesztette a hozzászólásod, bár ők akár hagyhatnak is megjegyzést jelezve mondjuk a szerkesztés okát. Kérjük, vedd figyelembe, hogy a normál felhasználók nem törölhetik a hozzászólásukat, miután már másvalaki válaszolt.</dd>
				</dl>
				<hr class="dashed" />
				<dl class="faq">
					<dt id="f2r2"><strong style="color:#FFE3A5;">Hogyan készíthetek szavazást?</strong></dt>
					<dd>Szavazást csak meghatározott szövetségi státusszal lehet indítani. Amikor egy új témát nyitsz vagy egy téma első hozzászólását szerkeszted, kattints a „Szavazás készítése” fülre az üzenet mező alatt. Ha nem látod ezt a fület, az azért lehet, mert nincs jogosultságod szavazás készítéséhez. Add meg a szavazás címét, majd legalább két választási lehetőséget mindegyiket új sorba írva. A „Felhasználónként válaszható lehetőségek” mező használatával megadhatod azt is, hogy egy felhasználó hány választási lehetőségre szavazhat; beállíthatsz a szavazásnak egy időkorlátot (napokban megadva); és végül választhatsz, hogy lehetséges legyen-e a szavazatokat megváltoztatatni.</dd>
				</dl>
				<hr class="dashed" />
				<dl class="faq">
					<dt id="f2r3"><strong style="color:#FFE3A5;">Hogyan szerkeszthetek vagy törölhetek egy szavazást?</strong></dt>
					<dd>A hozzászólásokhoz hasonlóan a szavazásokat is csak a készítő, a Proctor Conductor vagy egy Inspektor szerkesztheti. Egy szavazás szerkesztéséhez menj a téma első hozzászólásához – mindig ehhez tartozik a szavazás, és kattints a szerkeszt gombra. Ha még senki sem szavazott, a készítő még törölheti a szavazást, vagy megváltoztathatja a választási lehetőségeket, de ha már érkezett szavazat, csak a Proctor Conductor vagy egy Inspektor törölheti vagy szerkesztheti a szavazást. Így nem lehet manipulálni a szavazást a szavazási lehetőségek megváltoztatásával.</dd>
				</dl>
				<hr class="dashed" />
				<dl class="faq">
					<dt id="f2r4"><strong style="color:#FFE3A5;">Miért nem férek hozzá egy témához?</strong></dt>
					<dd>Néhány téma lehet, hogy csak bizonyos felhasználók, illetve csoportok számára érhető el. A fórum megtekintéséhez, olvasásához, benne hozzászólás küldéséhez vagy szavazás indításához különböző jogosultságok szükségesek. Ezek többsége Galaxis-, vagy Szövetségi státusz függő, de a Proctor Conductor által kinevezett hadúr is kaphat ilyen különleges jogosultságokat.</dd>
				</dl>
				<hr class="dashed" />
				<dl class="faq">
					<dt id="f2r5"><strong style="color:#FFE3A5;">Miért nem tudok szavazni?</strong></dt>
					<dd>Csak olyan hadurak vehetnek részt egy szavazásban, akik erre jogosultságot kapnak.</dd>
				</dl>
				<hr class="dashed" />
				<dl class="faq">
					<dt id="f2r6"><strong style="color:#FFE3A5;">Miért kaptam figyelmeztetést?</strong></dt>
					<dd>Az UFFIH idevonatkozó rendeleteit mindig figyelembe kell venni és annak megfelelően használni a fórumot, melyet a Proctor Conductor és az Inspektorok felügyelnek.</dd>
				</dl>
				<hr class="dashed" />
				<dl class="faq">
					<dt id="f2r7"><strong style="color:#FFE3A5;">Hogyan jelenthetek egy hozzászólást a moderátoroknak?</strong></dt>
					<dd>Menj a hozzászóláshoz, melyet jelenteni szeretnél, és  látnod kell egy gombot jelentem!! felirattal, mely erre való. Ha erre kattintasz, végigkísérésre kerülsz a hozzászólás jelentéséhez szükséges lépéseken.</dd>
				</dl>
				
		</div>

		<span class="corners-bottom"><span></span></span></div>
	</div>

	<div class="panel bg1">
		<div class="inner"><span class="corners-top"><span></span></span>

		<div class="content">
                    <h2 style="color:white;">Formázás és téma típusok</h2>
			
				<dl class="faq">
					<dt id="f3r0"><strong style="color:#FFE3A5;">Mi az a BBCode?</strong></dt>
					<dd>A BBCode a HTML nyelv egy speciális változata, mely nagy teret enged egy szövegrészlet megformázásához. A BBCode használatának engedélyezése az adminisztrátortól függ, de neked is lehetőséged van ki- vagy bekapcsolni a hozzászólásaidnál. A BBCode hasonló felépítésű, mint a HTML, kivéve hogy a címkék nem kacsacsőrök között („<” , ill. „>”), hanem szögletes zárójelben („[”, ill. „]”) vannak. További információért lásd a BBCode útmutatót, melyet a hozzászólásküldő oldalról érhetsz el.</dd>
				</dl>
				<hr class="dashed" />
				<dl class="faq">
					<dt id="f3r1"><strong style="color:#FFE3A5;">Használhatok HTML-t?</strong></dt>
					<dd>Nem. Nem lehetséges HTML-t küldeni, majd azt HTML-ként is megjeleníteni. A legtöbb HTML-lel létrehozható formázás BBCode használatával is elérhető.</dd>
				</dl>
				<hr class="dashed" />
				<dl class="faq">
					<dt id="f3r2"><strong style="color:#FFE3A5;">Mik azok a fejecskék?</strong></dt>
					<dd>A fejecskék, smiley-k vagy más néven emotikonok kis grafikák, melyekkel érzéseket és hangszínt lehet kifejezni. Például a :) vidámot/boldogot, a :( szomorút jelent. A használható emotikonok teljes listája megtalálható a hozzászólás küldésénél. Lehetőleg ne használj túl sok fejecskét, mert nehezen lesz olvasható a hozzászólás, ezért pedig egy Inspektor is kiszerkesztheti őket, vagy akár az egész hozzászólást törölheti. A Proctor Conductor beállíthat egy felső korlátot, melynél nem használhatsz több fejecskét egy hozzászólásban.</dd>
				</dl>
				<hr class="dashed" />
				<dl class="faq">
					<dt id="f3r3"><strong style="color:#FFE3A5;">Küldhetek képeket?</strong></dt>
					<dd>Igen, megjeleníthetsz képeket a hozzászólásaidban. Azonban, ha az adminisztrátor engedélyezte a csatolmányok hozzáadását, akkor a képeket egyenesen a fórumra is feltöltheted. Ellenkező esetben a képeket egy publikus, mindenki által elérhető szerveren kell tárolnod, és onnan belinkelned – például: http://www.akarmi.hu/en-kepem.gif. Nem tudsz belinkelni képeket a saját gépedről (hacsak az nem érhető el kívülről is), azonosítást igénylő oldalakról (mint például freemail, gmail, yahoo postafiókok), jelszóval védett weblapokról stb. A képek megjelenítéséhez használd az [img] BBCode címkét.</dd>
				</dl>
				<hr class="dashed" />
				<dl class="faq">
					<dt id="f3r4"><strong style="color:#FFE3A5;">Mik azok a globális közlemények?</strong></dt>
					<dd>A globális közlemények fontos információkat tartalmaznak, ezért olvasd el őket valahányszor csak tudod. A felhasználói vezérlőpultban és minden fórum tetején jelennek meg. Globális közlemények küldéséhez az adminisztrátor adhat jogosultságot.</dd>
				</dl>
				<hr class="dashed" />
				<dl class="faq">
					<dt id="f3r5"><strong style="color:#FFE3A5;">Mik azok a lezárt témák?</strong></dt>
					<dd>A lezárt témák olyan témák, melyekbe nem lehet hozzászólást küldeni vagy szavazni bennük. Egy téma lezárásának több oka lehet. Egy témát a Proctor Conductor, egy Inspektor vagy az arra kijelölt hadúr zárhat csak le és nyithat meg újra.</dd>
				</dl>
				
		</div>

		<span class="corners-bottom"><span></span></span></div>
	</div>

	<div class="panel bg2">
		<div class="inner"><span class="corners-top"><span></span></span>

		<div class="content">
                    <h2 style="color:white;">Az UFFIH jelenléte a fórumon</h2>
			
				<dl class="faq">
					<dt id="f4r0"><strong style="color:#FFE3A5;">Ki az a Proctor Conductor?</strong></dt>
					<dd>A Proctor Conductor  a fórum legmagasabb rangú és teljes jogú tagja. A fórum minden részletét szabályozhatja, többek között jogosultságokat adhat, kitilthat felhasználókat, csoportokat hozhat létre, Inspektorokat nevezhet ki, stb.</dd>
				</dl>
				<hr class="dashed" />
				<dl class="faq">
					<dt id="f4r1"><strong style="color:#FFE3A5;">Kik azok az Inspektorok?</strong></dt>
					<dd>Az Inspektorok olyan különleges jogosultságokkal rendelkező tagok, akik napról napra figyelemmel követik a fórumokat. Jogukban áll szerkeszteni, törölni a hozzászólásokat, valamint lezárni, megnyitni, áthelyezni, törölni, szétválasztani, összevonni és másolni a témákat az általuk moderált fórumban. Általánosságban az Inspektorok azért vannak, hogy meggátolják a témába nem illő, sértegető vagy támadó hangvételű hozzászólások küldését.</dd>
				</dl>
				<hr class="dashed" />
				<dl class="faq">
					<dt id="f4r2"><strong style="color:#FFE3A5;">Kit és hogy tudok értesíteni, ha a fórum tartalmával problémám van?</strong></dt>
					<dd>Bármilyen hozzászólás, melynek tartalmát zavarónak, sértőnek vagy szabálysértőnek érzel, a Bejelentés gombra kattintva jelezheted az UFFIH számára.</dd>
				</dl>
				
		</div>

		<span class="corners-bottom"><span></span></span></div>
	</div>

	<div class="panel bg1">
		<div class="inner"><span class="corners-top"><span></span></span>

		<div class="content">
                    <h2 style="color:white;">Készítők</h2>
			
				<dl class="faq">
					<dt id="f5r0"><strong style="color:#FFE3A5;">Ki készítette ezt a fórumot?</strong></dt>
					<dd>Ezt a szoftvert (eredeti formájában) a phpBB Group készítette, adta ki, és gyakorolja a szerzői jogokat felette. A GNU General Public License alatt érhető el, és szabadon terjeszthető. További információért lásd a linket.</dd>
				</dl>
				
		</div>

		<span class="corners-bottom"><span></span></span></div>
	</div>
</div>

<div id="page-footer">



<!--
	We request you retain the full copyright notice below including the link to www.phpbb.com.
	This not only gives respect to the large amount of time given freely by the developers
	but also helps build interest, traffic and use of phpBB3. If you (honestly) cannot retain
	the full copyright we ask you at least leave in place the "Powered by phpBB" line, with
	"phpBB" linked to www.phpbb.com. If you refuse to include even this then support on our
	forums may be affected.

	The phpBB Group : 2006
//-->

	
</div>

</div>



</body>
</html>