name: Django CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.11]

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r opengalactica/requirements.txt
        python opengalactica/manage.py makemigrations
        python opengalactica/manage.py migrate
        python opengalactica/manage.py makemigrations engine
        python opengalactica/manage.py migrate
    - name: Run Tests
      run: |
        cd opengalactica
        python manage.py test
